substitutions:
  reboot_timeout: 1d
  static_ip: '192.168.1.92'
  node_name: 'air-purifier'
  name: 'air purifier'

esphome:
  name: ${node_name}
  platform: ESP8266
  board: esp01_1m
  includes:
    - espsense.h
  libraries:
    - "ESPAsyncUDP"   # do not include if using an ESP32 board or device!
    - "ArduinoJson-esphomelib@5.13.3"

wifi:
  domain: !secret wifi_domain
  fast_connect: true
  manual_ip:
    static_ip: '192.168.20.92'
    gateway: '192.168.20.1'
    subnet: '255.255.255.0'
    dns1: '192.168.1.70'
    dns2: '192.168.1.80'
  networks:
   - ssid: !secret wifi_ssid
     password: !secret wifi_password
     hidden: true
  reboot_timeout: ${reboot_timeout}
  use_address: 192.168.20.92

# Enable logging
logger:
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800

api:

ota:

time:
  - platform: homeassistant
    id: homeassistant_time

sun:
  latitude: !secret latitude
  longitude: !secret longitude

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Outlet 1 Button"
    on_press:
      - switch.toggle: fakebutton
  - platform: template
    name: "${name} Running"
    filters:
      - delayed_off: 15s
    lambda: |-
      if (isnan(id(power_sensor).state)) {
        return {};
      } else if (id(power_sensor).state > 4) {
        // Running
        return true;
      } else {
        // Not running
        return false;
      }

switch:
  - platform: template
    name: "${name} POW Relay"
    optimistic: true
    id: fakebutton
    turn_on_action:
    - switch.turn_on: relay
    - light.turn_on: led
    turn_off_action:
    - switch.turn_off: relay
    - light.turn_off: led
  - platform: gpio
    id: relay
    pin: GPIO12

output:
  - platform: esp8266_pwm
    id: pow_blue_led
    pin:
      number: GPIO13
      inverted: True

light:
  - platform: monochromatic
    name: "${name} Blue LED"
    output: pow_blue_led
    id: led

sensor:
  - platform: wifi_signal
    name: "${name} WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "${name} Uptime"
  - platform: cse7766
    current:
      name: "${name} Current"
    voltage:
      id: voltage_sensor
      unit_of_measurement: V
      name: "${name} Voltage"
    power:
      name: "${name} POW Power"
      id: power_sensor
      on_value_range:
        - above: 3.0
          then:
            - light.turn_on: led
        - below: 2.0
          then:
            - light.turn_off: led
      unit_of_measurement: W

custom_component:
  # Create ESPSense instance, passing the ID of the sensor it should retrieve
  # power data from
- lambda: |-
    // Define "plugs"
    ESPSensePlug plug1 = ESPSensePlug(id(power_sensor), "50:C7:BF:9B:BD:37", "Air Purifier", 120.0);
    // Plug1 also measures voltage
    plug1.voltage_sid = voltage_sensor; // ID of voltage sensor
    // Add to ESPSense
    auto sense = new ESPSense();
    sense->addPlug(plug1);
    return {sense};

text_sensor:
  - platform: version
    name: "${name} ESPHome Version"
