substitutions:
  reboot_timeout: 1d
  name: 'bedroom-headboard'
  friendly_name: 'Bedroom Headboard'
  static_ip: '192.168.20.99'

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

packages:
  wifi: !include common/wifi.yml
  sensor_wifi: !include common/sensor_wifi.yml

esphome:
  name: "${name}"
  platformio_options:
    board_build.flash_mode: dio

time:
  - platform: homeassistant
    id: homeassistant_time

logger:
  level: DEBUG
  baud_rate: 0

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

sun:
  latitude: !secret latitude
  longitude: !secret longitude

output:
  - platform: ledc
    pin: GPIO3
    frequency: 19531Hz
    id: pwm_r
  - platform: ledc
    pin: GPIO0
    frequency: 19531Hz
    id: pwm_g
  - platform: ledc
    pin: GPIO1
    frequency: 19531Hz
    id: pwm_b
  - platform: ledc
    pin: GPIO4
    frequency: 19531Hz
    id: pwm_ww
  - platform: ledc
    pin: GPIO5
    frequency: 19531Hz
    id: pwm_cw

light:
  - platform: rgbww
    id: light_1
    name: "${friendly_name}"
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    cold_white: pwm_cw
    warm_white: pwm_ww
    warm_white_color_temperature: 2400 K
    cold_white_color_temperature: 6500 K
    effects:
    - automation:
        name: Sunrise
        sequence:
          - light.turn_on:
              id: light_1 #xy [0.65,0.41]
              red: 100% #255
              green: 45% #132
              blue: 0% #0
              white: 0%
              brightness: 10%
          - delay: 60s
          - light.turn_on:
              id: light_1 #xy [0.60,0.40]
              red: 100% #255
              green: 51.7% #145
              blue: 0% #0
              white: 0%
              brightness: 33% #85
              transition_length: 60s
          - delay: 60s
          - light.turn_on:
              id: light_1 #xy [0.48,0.40]
              red: 100% #255
              green: 51.7% #190
              blue: 0% #109
              white: 0%
              brightness: 66% #170
              transition_length: 60s
          - delay: 60s
          - light.turn_on:
              id: light_1 #xy [0.48,0.40]
              red: 100% #255
              green: 51.7% #190
              blue: 0% #109
              white: 1%
              color_temperature: 2400 K
              brightness: 66% #170
              transition_length: 60s
          - delay: 60s
          - light.turn_on:
              id: light_1 #xy [0.48,0.40]
              red: 100% #255
              green: 51.7% #190
              blue: 0% #109
              white: 100%
              color_temperature: 2400 K
              brightness: 66% #170
              transition_length: 60s
          - delay: 60s
          - light.turn_on:
              id: light_1
              white: 100%
              color_temperature: 2400 K
              brightness: 0%
              transition_length: 60s
          - delay: 1800s
          - light.turn_off:
              id: light_1

sensor:
  - platform: uptime
    name: "${name} Uptime Sensor"

  - platform: internal_temperature
    name: "${name} Internal Temperature"
    accuracy_decimals: 2
    update_interval: 30s

switch:
  - platform: restart
    name: ${name}-restart
    id: restart_switch
