esphome:
  name: bedroom_headboard 
  platform: ESP8266
  board: esp01_1m
wifi:
  ssid: 'bill wi the science fi'
  password: 'kit+april=awesome'
  domain: '.lan'
  manual_ip:
    static_ip: '192.168.1.99'
    gateway: '192.168.1.1'
    subnet: '255.255.255.0'
    dns1: '192.168.1.33'
    dns2: '192.168.1.1'
time:
  - platform: sntp
    timezone: America/Denver
    servers:
    - 'ntp.lan'
    id: sntp_time
logger:
api:
ota:
sensor:
  - platform: wifi_signal
    name: "WiFi Signal bedroom_headboard"
    update_interval: 60s
output:
  - platform: esp8266_pwm
    pin: 12
    frequency: 22000 Hz
    id: pwm_b
  - platform: esp8266_pwm
    pin: 13
    frequency: 22000 Hz
    id: pwm_g
  - platform: esp8266_pwm
    pin: 15
    frequency: 22000 Hz
    id: pwm_r
  - platform: esp8266_pwm
    pin: 14
    frequency: 22000 Hz
    id: pwm_cw
  - platform: esp8266_pwm
    pin: 4
    frequency: 22000 Hz
    id: pwm_ww
light:
  - platform: rgbww
    name: "H801 Light"
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    cold_white: pwm_cw 
    warm_white: pwm_ww
    warm_white_color_temperature: 2400 K
    cold_white_color_temperature: 6500 K
