substitutions:
  reboot_timeout: 1d
  name: 'bedroom-headboard'
  friendly_name: 'Bedroom Headboard'
  static_ip: '192.168.20.99'

packages:
  wifi: !include common/wifi.yml
  sensor_wifi: !include common/sensor_wifi.yml

esphome:
  name: "${name}"
  platform: ESP8266
  board: esp01_1m

time:
  - platform: homeassistant
    id: homeassistant_time

logger:

api:

ota:
  - platform: esphome
    password: !secret ota_password

sun:
  latitude: !secret latitude
  longitude: !secret longitude

output:
  - platform: esp8266_pwm
    pin: 15
    frequency: 1000 Hz
    id: pwm_r
    min_power: 0
    max_power: 0.95
  - platform: esp8266_pwm
    pin: 13
    frequency: 1000 Hz
    id: pwm_g
    min_power: 0
    max_power: 0.95
  - platform: esp8266_pwm
    pin: 12
    frequency: 1000 Hz
    id: pwm_b
    min_power: 0
    max_power: 0.95
  - platform: esp8266_pwm
    pin: 14
    frequency: 1000 Hz
    id: pwm_cw
    min_power: 0
    max_power: 0.95
  - platform: esp8266_pwm
    pin: 4
    frequency: 1000 Hz
    id: pwm_ww
    min_power: 0
    max_power: 0.95

light:
  - platform: rgbww
    id: light_1
    name: "${friendly_name}"
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    cold_white: pwm_cw
    warm_white: pwm_ww
    warm_white_color_temperature: 2400 K
    cold_white_color_temperature: 6500 K
    effects:
    - automation:
        name: Sunrise
        sequence:
          - light.turn_on:
              id: light_1 #xy [0.65,0.41]
              red: 100% #255
              green: 45% #132
              blue: 0% #0
              white: 0%
              brightness: 10%
          - delay: 60s
          - light.turn_on:
              id: light_1 #xy [0.60,0.40]
              red: 100% #255
              green: 51.7% #145
              blue: 0% #0
              white: 0%
              brightness: 33% #85
              transition_length: 60s
          - delay: 60s
          - light.turn_on:
              id: light_1 #xy [0.48,0.40]
              red: 100% #255
              green: 51.7% #190
              blue: 0% #109
              white: 0%
              brightness: 66% #170
              transition_length: 60s
          - delay: 60s
          - light.turn_on:
              id: light_1 #xy [0.48,0.40]
              red: 100% #255
              green: 51.7% #190
              blue: 0% #109
              white: 1%
              color_temperature: 2400 K
              brightness: 66% #170
              transition_length: 60s
          - delay: 60s
          - light.turn_on:
              id: light_1 #xy [0.48,0.40]
              red: 100% #255
              green: 51.7% #190
              blue: 0% #109
              white: 100%
              color_temperature: 2400 K
              brightness: 66% #170
              transition_length: 60s
          - delay: 60s
          - light.turn_on:
              id: light_1
              white: 100%
              color_temperature: 2400 K
              brightness: 0%
              transition_length: 60s
          - delay: 1800s
          - light.turn_off:
              id: light_1
