substitutions:
  reboot_timeout: 1d
  name: 'ble-tracker-olimex'
  friendly_name: 'BLE Tracker Olimex'
  static_ip: '192.168.20.82'

packages:
  ethernet: !include common/olimex-poe-iso-ethernet.yml

esp32:
  board: esp32-poe-iso
  framework:
    type: esp-idf

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

ota:
  platform: esphome
  password: !secret ota_password

logger:

api:
  encryption:
    key: !secret api_encryption_key
  reboot_timeout: ${reboot_timeout}

time:
  - platform: homeassistant
    id: homeassistant_time

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true

sensor:
  - platform: xiaomi_lywsd02mmc
    mac_address: !secret lywsd02mmc_mac_address
    bindkey: !secret lywsd02mmc_bindkey
    temperature:
      name: "Olimex LYWSD02MMC Temperature"
    humidity:
      name: "Olimex LYWSD02MMC Humidity"
    battery_level:
      name: "Olimex LYWSD02MMC Battery Level"
  - platform: xiaomi_lywsd03mmc
    mac_address: !secret lywsd03mmc_mac_address
    bindkey: !secret lywsd03mmc_bindkey
    temperature:
      name: "Olimex LYWSD03MMC Temperature"
    humidity:
      name: "Olimex LYWSD03MMC Humidity"
    battery_level:
      name: "Olimex LYWSD03MMC Battery Level"
  - platform: ble_rssi
    mac_address: !secret lywsd02mmc_mac_address
    name: "Olimex LYWSD02MMC RSSI"
  - platform: ble_rssi
    mac_address: !secret lywsd03mmc_mac_address
    name: "Olimex LYWSD03MMC RSSI"
  - platform: ble_rssi
    mac_address: !secret ekg_plus_mac_address
    name: "Olimex EKG+ RSSI"

  - platform: ble_rssi
    mac_address: "E2:A3:D2:13:68:7E"
    name: "Olimex Bedroom Shade 1 RSSI"
  - platform: ble_rssi
    mac_address: "C6:59:FC:37:F5:37"
    name: "Olimex Bedroom Shade 2 RSSI"
  - platform: ble_rssi
    mac_address: "A4:C1:38:9F:96:A9"
    name: "Olimex Cooler Thermometer RSSI"
  - platform: ble_rssi
    mac_address: "A4:C1:38:10:2A:E5"
    name: "Olimex Filament Storage 1 RSSI"
  - platform: ble_rssi
    mac_address: "A4:C1:38:40:2B:D4"
    name: "Olimex Filament Storage 2 RSSI"
  - platform: ble_rssi
    mac_address: "A4:C1:38:60:44:8B"
    name: "Olimex Filament Storage 3 RSSI"
  - platform: ble_rssi
    mac_address: "A4:C1:38:FF:2F:4A"
    name: "Olimex Freezer Thermometer RSSI"
  - platform: ble_rssi
    mac_address: "A4:C1:38:0A:8C:67"
    name: "Olimex Fridge Thermometer RSSI"
  - platform: ble_rssi
    mac_address: "C2:44:38:CB:5D:A2"
    name: "Olimex Sunroom Shade 1 RSSI"
  - platform: ble_rssi
    mac_address: "E4:F4:9A:A1:8B:F8"
    name: "Olimex Sunroom Shade 2 RSSI"
  - platform: ble_rssi
    mac_address: "C6:02:A9:65:BE:64"
    name: "Olimex Sunroom Shade 3 RSSI"
  - platform: ble_rssi
    mac_address: "CF:96:14:D5:10:05"
    name: "Olimex Sunroom Shade 4 RSSI"
  - platform: ble_rssi
    mac_address: "CA:A4:30:0F:52:FC"
    name: "Olimex Sunroom Shade 5 RSSI"
