substitutions:
  reboot_timeout: 1d
  node_name: 'ir-transmitter'
  name: 'IR Transmitter'
  static_ip: '192.168.20.93'

packages:
  s31_base: !include common/s31_base.yml
  wifi: !include common/wifi.yml
  sun: !include common/sun.yml

# GPIO	Component	Description
# 04	LED1i (52)	Blue LED - Link status
# 05	IRrecv (51)	IR Receiver
# 13	Button1 (17)	Button
# 14	IRsend (8)	IR Transmitter
  
remote_transmitter:
  pin: GPIO14
  carrier_duty_percent: 50%
  
remote_receiver:
  id: rcvr
  pin:
    number: GPIO5
    inverted: True
  tolerance: 55%
  dump: all

# Use the blue LED as a status light.
#   Blink slowly = Temporary issue (WiFi/MQTT disconnected, sensor unavailable, ...)
#   Blink quickly = Error encountered
status_led:
    pin: GPIO4
