substitutions:
  reboot_timeout: 1d
  node_name: 'living-room-floor-lamp'
  name: 'Living Room Floor Lamp'
  static_ip: '192.168.20.96'
  espsense_mac_address: 50:C7:BF:FC:D1:99
  # Not currently used:
  #espsense_device_id: FBEA4BC05451D81E7466C84BE4D976ACA3D82290

packages:
  s31_base: !include common/s31_base.yml
  wifi: !include common/wifi.yml
  sun: !include common/sun.yml
  s31_power: !include common/s31_power.yml
  #espsense: !include common/espsense.yml
