substitutions:
  reboot_timeout: 1d
  name: 'heatpump'
  friendly_name: 'Mitsu Heat Pump'
  static_ip: '192.168.20.98'

packages:
  wifi: !include common/wifi.yml
  sensor_wifi: !include common/sensor_wifi.yml

esphome:
  name: ${name}

esp8266:
  board: esp01_1m

logger:
  level: DEBUG
  baud_rate: 0 # disable serial port logging so that UART0 can be used for heatpump

api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

  # Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

text_sensor:
  - platform: version
    name: ${name} ESPHome Version

sensor:
  - platform: uptime
    name: ${name} Uptime

external_components:
  - source: github://geoffdavis/esphome-mitsubishiheatpump

climate:
  - platform: mitsubishi_heatpump
    name: "${friendly_name}"
    hardware_uart: UART0
