substitutions:
  reboot_timeout: 1d
  node_name: 'sunroom-air-quality'
  name: 'Sunroom Air Quality'
  static_ip: '192.168.20.94'

esphome:
  board: nodemcu-32s
  includes:
    - aqi_custom_sensor.h
  libraries:
    - "Adafruit PM25 AQI Sensor"
    - SPI
  name: ${node_name}
  platform: ESP32

i2c:
  sda: 23
  scl: 22

wifi:
  domain: !secret wifi_domain
  fast_connect: true
  manual_ip:
    static_ip: ${static_ip}
    gateway: '192.168.20.1'
    subnet: '255.255.255.0'
    dns1: '192.168.1.70'
    dns2: '192.168.1.80'
  networks:
   - ssid: !secret wifi_ssid
     password: !secret wifi_password
     hidden: true
  reboot_timeout: ${reboot_timeout}
  use_address: ${static_ip}

time:
  - platform: homeassistant
    id: homeassistant_time

esp32_ble_tracker:

logger:
  level: DEBUG

api:
  reboot_timeout: ${reboot_timeout}

ota:

sensor:
  - platform: wifi_signal
    name: "${name} WiFi Signal"
    update_interval: 60s
  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:63:F1:5D'
    temperature:
      name: "Bedroom Plant Temperature"
      filters:
        - offset: 1.38
    moisture:
      name: "Bedroom Plant Moisture"
    illuminance:
      name: "Bedroom Plant Illuminance"
    conductivity:
      name: "Bedroom Plant Soil Conductivity"
    battery_level:
      name: "Bedroom Plant Battery Level"
  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:63:EF:C8'
    temperature:
      name: "Kitchen Plant Temperature"
      filters:
        - offset: 1.61
    moisture:
      name: "Kitchen Plant Moisture"
    illuminance:
      name: "Kitchen Plant Illuminance"
    conductivity:
      name: "Kitchen Plant Soil Conductivity"
    battery_level:
      name: "Kitchen Plant Battery Level"
  - platform: scd30
    co2:
      name: "${name} CO2"
      accuracy_decimals: 1
    temperature:
      name: "${name} Temperature"
      accuracy_decimals: 2
    humidity:
      name: "${name} Humidity"
      accuracy_decimals: 1
    address: 0x61
    update_interval: 5s
  - platform: custom
    lambda: |-
      auto aqi_sensor = new PMSA003I();
      App.register_component(aqi_sensor);
      return {aqi_sensor->pm10, aqi_sensor->pm25, aqi_sensor->pm100};
    sensors:
    - name: "{name} Particulate Matter <1.0µm Concentration"
      unit_of_measurement: "µg/m^3"
      filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 5
    - name: "${name} Particulate Matter <2.5µm Concentration"
      unit_of_measurement: "µg/m^3"
      filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 5
    - name: "{name} Particulate Matter <10.0µm Concentration"
      unit_of_measurement: "µg/m^3"
      filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 5
