substitutions:
  reboot_timeout: 1d
  name: 'sunroom-air-quality'
  friendly_name: 'Sunroom Air Quality'
  static_ip: '192.168.20.94'

packages:
  wifi: !include common/wifi.yml

esp32:
  board: esp32thing_plus
  framework:
    type: esp-idf

esphome:
  name: ${name}

ota:

i2c:
  sda: 23
  scl: 22

time:
  - platform: homeassistant
    id: homeassistant_time

logger:
  level: DEBUG 

api:
  reboot_timeout: ${reboot_timeout}

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

sensor:
  - platform: scd30
    co2:
      name: "${friendly_name} CO2"
      accuracy_decimals: 1
    temperature:
      name: "${friendly_name} Temperature"
      accuracy_decimals: 2
    humidity:
      name: "${friendly_name} Humidity"
      accuracy_decimals: 1
    address: 0x61
    update_interval: 60s
    altitude_compensation: 1617m
  - platform: pmsa003i
    pm_1_0:
      name: "${friendly_name} PM1.0"
      filters:
      - median:
          window_size: 3
          send_every: 3
    pm_2_5:
      name: "${friendly_name} PM2.5"
      filters:
      - median:
          window_size: 3
          send_every: 3
    pm_10_0:
      name: "${friendly_name} PM10.0"
      filters:
      - median:
          window_size: 3
          send_every: 3
    pmc_0_3:
      name: "${friendly_name} Particulate Matter <0.3µm Concentration"
      filters:
      - median:
          window_size: 3
          send_every: 3
    pmc_0_5:
      name: "${friendly_name} Particulate Matter <0.5µm Concentration"
      filters:
      - median:
          window_size: 3
          send_every: 3
    pmc_1_0:
      name: "${friendly_name} Particulate Matter <1.0µm Concentration"
      filters:
      - median:
          window_size: 3
          send_every: 3
    pmc_2_5:
      name: "${friendly_name} Particulate Matter <2.5µm Concentration"
      filters:
      - median:
          window_size: 3
          send_every: 3
    pmc_5_0:
      name: "${friendly_name} Particulate Matter <5.0µm Concentration"
      filters:
      - median:
          window_size: 3
          send_every: 3
    pmc_10_0:
      name: "${friendly_name} Particulate Matter <10.0µm Concentration"
      filters:
      - median:
          window_size: 3
          send_every: 3
    update_interval: 60s
