esphome:
  name: tree
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain
  manual_ip:
    static_ip: '192.168.1.97'
    gateway: '192.168.1.1'
    subnet: '255.255.255.0'
    dns1: '192.168.1.33'
    dns2: '192.168.1.29'

# Enable logging
logger:
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800

api:

ota:

time:
  - platform: homeassistant
    id: homeassistant_time

sun:
  latitude: !secret latitude
  longitude: !secret longitude

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Outlet 1 Button"
    on_press:
      - switch.toggle: fakebutton
  - platform: template
    name: "Tree Running"
    filters:
      - delayed_off: 15s
    lambda: |-
      if (isnan(id(power).state)) {
        return {};
      } else if (id(power).state > 4) {
        // Running
        return true;
      } else {
        // Not running
        return false;
      }

switch:
  - platform: template
    name: "Tree POW Relay"
    optimistic: true
    id: fakebutton
    turn_on_action:
    - switch.turn_on: relay
    - light.turn_on: led
    turn_off_action:
    - switch.turn_off: relay
    - light.turn_off: led
  - platform: gpio
    id: relay
    pin: GPIO12

output:
  - platform: esp8266_pwm
    id: pow_blue_led
    pin:
      number: GPIO13
      inverted: True

light:
  - platform: monochromatic
    name: "Tree Blue LED"
    output: pow_blue_led
    id: led

sensor:
  - platform: wifi_signal
    name: "Tree WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "Tree Uptime"
  - platform: cse7766
    update_interval: 2s
    current:
      name: "Tree Current"
    voltage:
      name: "Tree Voltage"
    power:
      name: "Tree POW Power"
      id: power
      on_value_range:
        - above: 3.0
          then:
            - light.turn_on: led
        - below: 2.0
          then:
            - light.turn_off: led

text_sensor:
  - platform: version
    name: "Tree ESPHome Version"
