substitutions:
  reboot_timeout: 1d
  node_name: 'uv-light'
  name: 'UV Light'
  static_ip: '192.168.20.97'
  espsense_mac_address: 50:C7:BF:51:5F:DE
  # Not currently used:
  # espsense_device_id: 3CE77A0F9C7848948A8CCBAFD3797AEB3348F3CB

packages:
  s31_base: !include common/s31_base.yml
  wifi: !include common/wifi.yml
  sun: !include common/sun.yml
  s31_power: !include common/s31_power.yml
  #espsense: !include common/espsense.yml
