sensor:
  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:63:F1:5D'
    temperature:
      name: "Bedroom Plant Temperature"
      filters:
        - offset: 1.38
    moisture:
      name: "Bedroom Plant Moisture"
    illuminance:
      name: "Bedroom Plant Illuminance"
    conductivity:
      name: "Bedroom Plant Soil Conductivity"
    battery_level:
      name: "Bedroom Plant Battery Level"
