sensor:
  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:63:EF:C8'
    temperature:
      name: "Kitchen Plant Temperature"
      filters:
        - offset: 1.61
    moisture:
      name: "Kitchen Plant Moisture"
    illuminance:
      name: "Kitchen Plant Illuminance"
    conductivity:
      name: "Kitchen Plant Soil Conductivity"
    battery_level:
      name: "Kitchen Plant Battery Level"
