esphome:
  name: "${name}"

esp8266:
  board: esp01_1m

# Enable logging
logger:
  baud_rate: 0

api:

ota:
  - platform: esphome
    password: !secret ota_password

time:
  - platform: homeassistant
    id: homeassistant_time

text_sensor:
  - platform: version
    name: "${friendly_name} ESPHome Version"
